#server
MOVER: 0.5
SALTAR: 0.33
COMANDO_DERECHA: 1
COMANDO_IZQUIERDA: 2
COMANDO_AGACHARSE: 3
COMANDO_MIRAR_HACIA_ARRIBA: 4
COMANDO_SALTO_Y_ALETEO: 5
COMANDO_DISPARO: 6
COMANDO_AGARRAR: 7
EXCEPCION_ESPERADA: "Se produjo una excepcion esperada: "
EXCEPCION_INESPERADA: "Se produjo una excepcion inesperada: "
EXCEPCION_DESCONOCIDA: "Se produjo una excepcion desconocida. "
RW_CLOSE: 2
ALCANCE_SNIPER: 64
MUNICIONES_SNIPER: 3
ALCANCE_AK47: 13
MUNICIONES_AK47: 30
ID_GRANADA: 1
ID_PP_LASER: 2
ID_AK47: 3 
ID_MAGNUM: 4
ID_SHOTGUN: 5
ID_SNIPER: 6
FPS: 30
ALCANCE_MAGNUM: 20
MUNICIONES_MAGNUM: 6
TILE_A_METRO: 10
ALCANCE_MINIMO_PP_LASER: 35
ALCANCE_MAXIMO_PP_LASER: 38
MUNICIONES_PP_LASER: 12
CODIGO_PATO: 5
CODIGO_ARMA: 6
CODIGO_BALA: 7
CODIGO_ARMADURA: 8
CODIGO_CASCO: 9
CODIGO_CAJA: 10
CODIGO_CANTIDADES: 11
FIN_MENSAJE: 254
FIN_COMUNICACION: 255
EXIT_SERVER: "q"
ALCANCE_MINIMO_SHOTGUN: 7
ALCANCE_MAXIMO_SHOTGUN: 9
MUNICIONES_SHOTGUN: 2
PERDIGONES_POR_DISPARO_SG: 6
MSJ_ERROR_FORMATO: "Error de formato: El esperado es './server <puerto>'.\n"
EXITO: 0
FALLA: 1
POS_SERVICIO: 1
ARGUMENTOS_ESPERADOS: 2

#common
CANTIDAD_MAXIMA_ACCIONES: 20

#client
COMANDO_EXIT: 'X'
COMANDO_DERECHA: 'D'
COMANDO_IZQUIERDA: 'A'
COMANDO_AGACHAR: 'S'
COMANDO_MIRAR_ARRIBA: 'W'
COMANDO_SALTAR: ' '
COMANDO_DISPARAR: 'J'
COMANDO_AGARRAR: 'K'
RUTA_SPR_PATO: "/sprites-pato-blanco.png"
RUTA_SPR_AK: "/sprites-ak47.png"
RUTA_SPR_CAJAS: "/sprites-cajas.png"
RUTA_SPR_ARMADURAS: "/sprites-armaduras.png"
RUTA_SPR_ESCOPETA: "/sprites-escopeta.png"
RUTA_SPR_LASER: "/sprites-laser.png"
RUTA_SPR_PISTOLA: "/sprites-pistola.png"
RUTA_SPR_SNIPER: "/sprites-sniper.png"
RUTA_FUENTE: "/fuente_arcade.ttf"
MSJ_ERROR_TFF: "Error al inicializar SDL_ttf: "
MSJ_ERROR_RENDER_TXT: "Error al renderizar texto: "
PUNTAJE_STR: "Puntaje: "
SONIDO_AK: "/ak.mp3"
SONIDO_ESCOPETA: "/escopeta.mp3"
SONIDO_EXPLOSION: "/explosion.mp3"
SONIDO_LASER: "/laser.mp3"
SONIDO_PISTOLA: "/pistola.mp3"
SONIDO_SNIPER: "/sniper.mp3"
CUALQUIER_CANAL_LIBRE: -1
CANTIDAD_DE_REPRODUCCIONES: 0
TAMANIO_FUENTE: 24
ANCHO_VENTANA: 960
ALTO_VENTANA: 720
MAX_COORD_X: 200
MAX_COORD_Y: 160
OFFSET_Y: 0.03
ANGULO_NULO: 0.0
ANGULO_270: 270.0
ESCALA_SPRITES_GRANDES: 0.07
ESCALA_SPRITES_MEDIANOS: 0.04
ESCALA_SPRITES_CHICOS: 0.02
MIN_INTENSIDAD_RGB: 0
MED_INTENSIDAD_RGB: 128
MAX_INTENSIDAD_RGB: 255
RGB_AUX_MARRON_1: 69
RGB_AUX_MARRON_2: 19
ESTADO_PARADO: 0
ESTADO_AGACHADO: 1
ESTADO_SALTANDO: 2
ESTADO_ALETEANDO: 3
ESTADO_CAYENDO: 4
ESTADO_CAMINANDO: 5
CANTIDAD_SPRITES_CAMINAR: 6
POS_SPRITE_PARADO: 0
POS_SPRITE_AGACHADO: 9
POS_SPRITE_SALTANDO: 7
POS_SPRITE_ALETEANDO: 11
POS_SPRITE_CAYENDO: 8
POS_INICIAL_PATO_TABLERO: 10
GAP_PATO_TABLERO: 0.1
X_INICIAL_PUNTAJE: 100
Y_INICIAL_PUNTAJE: 30
GAP_PUNTAJE_TABLERO: 72
VOLUMEN_MUSICA: 0
FRECUENCIA_HZ: 44100
BUFFER_AUDIO: 2048
AUDIO_ESTEREO: 2
SLEEP: 100
DUCK_GAME_STR: "Duck Game"
RUTA_MAPA_1: "/mapa1.png"
RUTA_MAPA_2: "/mapa2.png"
RUTA_WIN_SCREEN: "/winscreen.png"
RUTA_LOSE_SCREEN: "/losescreen.png"
MUSICA_FONDO: "/arcade-song.mp3"
ERROR_INICIAR_MIX: "Error al inicializar SDL_mixer: "
ERROR_CARGAR_MUSICA: "Error al cargar la musica de fondo: "
TIRA_COMPLETA_SPRITES: 6
MEDIA_TIRA_SPRITES: 3
TIRA_COMPLETA_CAJAS: 4
TAMANIO_SPRITE_GRANDE: 32
TAMANIO_SPRITE_MEDIANO: 16
TAMANIO_SPRITE_CHICO: 8
INICIO_PATO_X: 1
INICIO_PATO_Y: 10
INICIO_PATO_QUACK_X: 194
INICIO_PATO_QUACK_Y: 10
INICIO_CAJA_X: 183
INICIO_CAJA_Y: 20
INICIO_ARMADURA_X: 387
INICIO_ARMADURA_Y: 13
INICIO_CASCO_X: 387
INICIO_CASCO_Y: 213
INICIO_AK_47_X: 1
INICIO_AK_47_Y: 19
INICIO_BALAS_AK_X: 2
INICIO_BALAS_AK_Y: 205
INICIO_ESCOPETA_X: 1
INICIO_ESCOPETA_Y: 25
INICIO_BALAS_ESCOPETA_X: 48
INICIO_BALAS_ESCOPETA_Y: 119
INICIO_MANGUM_X: 1
INICIO_MAGNUM_Y: 47
INICIO_BALAS_MAGNUM_X: 48
INICIO_BALAS_MAGNUM_Y: 89
INICIO_SNIPER_X: 36
INICIO_SNIPER_Y: 237
INICIO_BALAS_SNIPER_X: 35
INICIO_BALAS_SNIPER_Y: 62
INICIO_LASER_X: 336
INICIO_LASER_Y: 94
INICIO_BALAS_LASER_X: 1
INICIO_BALAS_LASER_Y: 138
INICIO_CASCO_LOOT_X: 602
INICIO_CASCO_LOOT_Y: 316
INICIO_ARMADURA_LOOT_X: 585
INICIO_ARMADURA_LOOT_Y: 289