#server
ALCANCE_SNIPER: 64
MUNICIONES_SNIPER: 3
ALCANCE_AK47: 13
MUNICIONES_AK47: 30
FPS: 30
ALCANCE_MAGNUM: 20
MUNICIONES_MAGNUM: 6
ALCANCE_MINIMO_PP_LASER: 35
ALCANCE_MAXIMO_PP_LASER: 38
MUNICIONES_PP_LASER: 12
ALCANCE_MINIMO_SHOTGUN: 7
ALCANCE_MAXIMO_SHOTGUN: 9
MUNICIONES_SHOTGUN: 2
PERDIGONES_POR_DISPARO_SG: 6
LASERS_POR_DISPARO_PP: 3